version: '2'
services:
  healthapp1-app:
    image: healthapp1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://healthapp1-postgresql:5432/healthapp1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://healthapp1-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://healthapp1-elasticsearch:9200
    ports:
      - 8080:8080
  healthapp1-postgresql:
    extends:
      file: postgresql.yml
      service: healthapp1-postgresql
  healthapp1-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: healthapp1-elasticsearch
